version: "3.8"

services:
  hugo:
    image: registry.cn-shenzhen.aliyuncs.com/nengjie/hugo:debian-nightly          # 固定版本可改为例如 hugomods/hugo:0.127.0
    container_name: hugo_site
    working_dir: /src                    # Hugo 镜像默认工作目录
    volumes:
      - .:/src                      # 将本地 Hugo 源码映射进去
#      - ./hugo_cache:/tmp/hugo_cache     # 可选：启用构建缓存，加快二次编译
    command: server --bind 0.0.0.0 --baseURL http://localhost --disableFastRender
    ports:
      - "1313:1313"                      # 访问 http://localhost:1313
    environment:
      - HUGO_ENV=development             # 根据需要改为 production
    restart: unless-stopped
