baseURL = "http://47.119.134.61"
# 语言编码 英文：en， 中文：zh-cn
defaultContentLanguage = "zh-cn"
#defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
theme = "gokarna"
title = "能捷"
copyright = '© 2023 ABC Widgets, Inc.'

[params]
  avatarAltText = "avatar"
  avatarSize = "size-s"
  avatarURL = "/images/avatar3.webp"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  customFooterHTML = '''

    <script>console.log("Custom script or import");</script>
    <script>
    // 获取所有具有特定class的div元素
    var divsToHide = document.querySelectorAll('footer.footer');
     // 遍历这些元素并隐藏它们
    divsToHide.forEach(function(div) {
        //div.innerHTML = ''; // 清空这些div的内容
        div.style.display = 'none';
    });
  </script>
  '''

  description = "分布式爬虫，系统架构，逆向，WEB开发"
#  footer = "The Marauders"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages

  socialIcons = [
#    {name = "twitter", url = "https://example.com"},
#    {name = "linkedin", url = "https://example.com"},
#    {name = "stackoverflow", url = "https://example.com"},
#    {name = "dribbble", url = "https://example.com"},
#    {name = "instagram", url = "https://example.com"},
#    {name = "twitch", url = "https://example.com"},
#    {name = "email", url = "mailto:example@example.com"}

     {name = "python", url = "/svg/icons/python.svg"},
     {name = "go", url = "/svg/icons/go.svg"},
     {name = "docker", url = "/svg/icons/docker.svg"},
     {name = "scrapy", url = "/svg/icons/scrapy.svg"},
     {name = "flask", url = "/svg/icons/flask.svg"},
     {name = "gin", url = "/svg/icons/gin.svg"},
     {name = "pytorch", url = "/svg/icons/pytorch.svg"},
  ]

[menu]
  [[menu.main]]
    name = "主页" # Home
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "文章" # Posts
    pre = "<span data-feather='book'></span>"
    url = "/ /"
    weight = 2

  [[menu.main]]
    name = "项目" # Projects
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "标签" # Tags
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/gokarna-theme/gokarna-hugo"
    weight = 5

#  [[menu.main]]
#    identifier = "buymeacoffee"
#    pre = "<span data-feather='coffee'></span>"
#    url = "https://www.buymeacoffee.com/avijitgupta"
#    weight = 6

#  [[menu.main]]
#    identifier = "rss"
#    pre = "<span data-feather='rss'></span>"
#    url = "/index.xml"
#    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true